!function(t){t.fn.slabText=function(e){var i={fontRatio:.78,forceNewCharCount:!0,wrapAmpersand:!0,headerBreakpoint:null,viewportBreakpoint:null,noResizeEvent:!1,resizeThrottleTime:300,maxFontSize:999,postTweak:!0,precision:3,minCharsPerLine:0};return t("body").addClass("slabtexted"),this.each(function(){e&&t.extend(i,e);var a=t(this),n=t("span.slabtext",a).length,r=n?[]:String(t.trim(a.text())).replace(/\s{2,}/g," ").split(" "),o=null,s=null,d=i.fontRatio,l=i.forceNewCharCount,h=i.headerBreakpoint,p=i.viewportBreakpoint,c=i.postTweak,f=i.precision,m=i.resizeThrottleTime,u=i.minCharsPerLine,w=null,v=t(window).width(),g=a.find("a:first").attr("href")||a.attr("href"),b=g?a.find("a:first").attr("title"):"";if(!(!n&&u&&r.join(" ").length<u)){var y=function(){var t=jQuery('<div style="display:none;font-size:1em;margin:0;padding:0;height:auto;line-height:1;border:0;">&nbsp;</div>').appendTo(a),e=t.height();return t.remove(),e},x=function(){var e,m=a.width();if(0!==m){if(a.removeClass("slabtextdone slabtextinactive"),p&&p>v||h&&h>m)return a.addClass("slabtextinactive"),void 0;if(e=y(),n||!l&&e==o)o=e;else{o=e;var w,x,j,T=Math.min(60,Math.floor(m/(o*d))),C=0,N=[],z="",k="",B="";if(T!=s){for(s=T;C<r.length;){for(k="";k.length<s&&(z=k,k+=r[C]+" ",!(++C>=r.length)););u&&(w=r.slice(C).join(" "),w.length<u&&(k+=w,z=k,C=r.length+2)),x=s-z.length,j=k.length-s,j>x&&z.length>=(u||2)?(B=z,C--):B=k,B=t("<div/>").text(B).html(),i.wrapAmpersand&&(B=B.replace(/&amp;/g,'<span class="amp">&amp;</span>')),B=t.trim(B),N.push('<span class="slabtext">'+B+"</span>")}a.html(N.join(" ")),g&&a.wrapInner('<a href="'+g+'" '+(b?'title="'+b+'" ':"")+"/>")}}t("span.slabtext",a).each(function(){var e,a,n,r=t(this),s=r.text(),d=s.split(" ").length>1;c&&r.css({"word-spacing":0,"letter-spacing":0}),a=m/r.width(),n=parseFloat(this.style.fontSize)||o,r.css("font-size",Math.min((n*a).toFixed(f),i.maxFontSize)+"px"),e=c?m-r.width():!1,e&&r.css((d?"word":"letter")+"-spacing",(e/(d?s.split(" ").length-1:s.length)).toFixed(f)+"px")}),a.addClass("slabtextdone")}};x(),i.noResizeEvent||t(window).resize(function(){t(window).width()!=v&&(v=t(window).width(),clearTimeout(w),w=setTimeout(x,m))})}})}}(jQuery),/*!
* FitVids 1.0
*
* Copyright 2013, Chris Coyier - http://css-tricks.com + Dave Rupert - http://daverupert.com
* Credit to Thierry Koblentz - http://www.alistapart.com/articles/creating-intrinsic-ratios-for-video/
* Released under the WTFPL license - http://sam.zoy.org/wtfpl/
*
* Date: Thu Sept 01 18:00:00 2011 -0500
*/
function(t){"use strict";t.fn.fitVids=function(e){var i={customSelector:null};if(!document.getElementById("fit-vids-style")){var a=document.createElement("div"),n=document.getElementsByTagName("base")[0]||document.getElementsByTagName("script")[0],r="&shy;<style>.fluid-width-video-wrapper{width:100%;position:relative;padding:0;}.fluid-width-video-wrapper iframe,.fluid-width-video-wrapper object,.fluid-width-video-wrapper embed {position:absolute;top:0;left:0;width:100%;height:100%;}</style>";a.className="fit-vids-style",a.id="fit-vids-style",a.style.display="none",a.innerHTML=r,n.parentNode.insertBefore(a,n)}return e&&t.extend(i,e),this.each(function(){var e=["iframe[src*='player.vimeo.com']","iframe[src*='youtube.com']","iframe[src*='youtube-nocookie.com']","iframe[src*='kickstarter.com'][src*='video.html']","object","embed"];i.customSelector&&e.push(i.customSelector);var a=t(this).find(e.join(","));a=a.not("object object"),a.each(function(){var e=t(this);if(!("embed"===this.tagName.toLowerCase()&&e.parent("object").length||e.parent(".fluid-width-video-wrapper").length)){var i="object"===this.tagName.toLowerCase()||e.attr("height")&&!isNaN(parseInt(e.attr("height"),10))?parseInt(e.attr("height"),10):e.height(),a=isNaN(parseInt(e.attr("width"),10))?e.width():parseInt(e.attr("width"),10),n=i/a;if(!e.attr("id")){var r="fitvid"+Math.floor(999999*Math.random());e.attr("id",r)}e.wrap('<div class="fluid-width-video-wrapper"></div>').parent(".fluid-width-video-wrapper").css("padding-top",100*n+"%"),e.removeAttr("height").removeAttr("width")}})})}}(window.jQuery||window.Zepto),function(){jQuery(function(){return $("h1").slabText({}),$(".video-holder").fitVids()})}.call(this);